language: swift
os: osx
osx_image: xcode11.3

xcode_project: Package.swift # path to your xcodeproj folder
xcode_scheme: MyWebsite
xcode_destination: platform=My Mac



matrix:
  include:
    - language: generic
      script:
        - pip install pygments
    - language: swift
    - script:
        - wget https://github.com/JohnSundell/Publish/archive/0.4.0.tar.gz
        - tar -xzvf 0.4.0.tar.gz
        - cd Publish-0.4.0
        - make install
        - cd ..
        - publish generate

after_succesfull: swift build
