matrix:
  include:
    - os: osx
      osx_image: xcode11.3
      sudo: required

before_install:
  - git clone https://github.com/IBM-Swift/Package-Builder.git
  - brew install python
  - pip install pygments

script:
  - ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR
