language: python
osx_image: xcode11.3

before_install:
  - wget https://github.com/JohnSundell/Publish/archive/0.4.0.tar.gz
  - tar -xzvf 0.4.0.tar.gz
  - cd Publish-0.4.0
  - make install
  - cd ..
  - pip install pygments
install: publish generate
