matrix:
  include:
    - os: osx
      osx_image: xcode11.3
      sudo: required
      env: SWIFT_SNAPSHOT=5.1

before_install:
  - git clone https://github.com/IBM-Swift/Package-Builder.git
  - python3 -m pip install pygments
  - wget https://github.com/JohnSundell/Publish/archive/0.4.0.tar.gz
  - tar -xzvf 0.4.0.tar.gz
  - cd Publish-0.4.0
  - make install
  - cd ..

script:
  - ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR
  - publish generate
