language: swift
os: osx
osx_image: xcode11.3



matrix:
  include:
    - language: python
      script:
        - pip install pygments
    - language: swift
    - script:
        - wget https://github.com/JohnSundell/Publish/archive/0.4.0.tar.gz
        - tar -xzvf 0.4.0.tar.gz
        - cd Publish-0.4.0
        - make install
        - cd ..
        - install: publish generate
